---
# Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: petstore
---
# Secret for database credentials
apiVersion: v1
kind: Secret
metadata:
  name: postgres-credentials
  namespace: petstore
type: Opaque
stringData:
  POSTGRES_USER: myuser
  POSTGRES_PASSWORD: secret
  POSTGRES_DB: petstore
---
# ConfigMap for application configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: swaggerql-config
  namespace: petstore
data:
  local.yaml: |
    # Add your local configuration here
  openapi.yaml: |
    # Add your OpenAPI specification here
---
# PostgreSQL StatefulSet
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-db
  namespace: petstore
spec:
  serviceName: postgres-service
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:11-alpine
        ports:
        - containerPort: 5432
          name: postgres
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: POSTGRES_DB
        volumeMounts:
        - name: postgres-storage
          mountPath: /var/lib/postgresql/data
        - name: init-scripts
          mountPath: /docker-entrypoint-initdb.d/
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          exec:
            command:
            - /bin/sh
            - -c
            - pg_isready -U myuser
          initialDelaySeconds: 30
          periodSeconds: 10
      volumes:
      - name: init-scripts
        emptyDir: {}
  volumeClaimTemplates:
  - metadata:
      name: postgres-storage
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 10Gi
---
# PostgreSQL Service
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: petstore
  labels:
    app: postgres
spec:
  type: ClusterIP
  ports:
  - port: 5432
    targetPort: 5432
    protocol: TCP
    name: postgres
  selector:
    app: postgres
  clusterIP: None
---
# SwaggerQL Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: swaggerql
  namespace: petstore
  labels:
    app: swaggerql
spec:
  replicas: 2
  selector:
    matchLabels:
      app: swaggerql
  template:
    metadata:
      labels:
        app: swaggerql
    spec:
      containers:
      - name: swaggerql
        image: swaggerql/swaggerql-postgres:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgres-credentials
              key: POSTGRES_DB
        - name: DATABASE_HOST
          value: "postgres-service"
        - name: DATABASE_PORT
          value: "5432"
        volumeMounts:
        - name: config-volume
          mountPath: /app/config
          readOnly: true
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 5
      volumes:
      - name: config-volume
        configMap:
          name: swaggerql-config
---
# SwaggerQL Service
apiVersion: v1
kind: Service
metadata:
  name: swaggerql-service
  namespace: petstore
  labels:
    app: swaggerql
spec:
  type: LoadBalancer
  ports:
  - port: 8000
    targetPort: 8000
    protocol: TCP
    name: http
  selector:
    app: swaggerql
